### ISSUE TITLE
Define project management environment

### ISSUE THREAD

**Issue by jfgossage** [jfgossage/Ayudante#1]
This is the master task for this activity.

Each task will have an associated documentation file which will serve several purposes:
- Describes how the task was performed. Initially describes how the task will be performed but will always be modified to describe how it was actually done.
- Serves as initial documentation for the code that implements this task in an automated fashion as part of the automated creation of Docker containers for the development environment of this project.

Since the GitHub connector does not support sub-tasks each sub-task listed here will link to the
appropriate task.
Activity list:
- [ ] Setup Git on local machine. https://github.com/jfgossage/issues/2
- [ ] Setup GitHub account. https://github.com/jfgossage/issues/3
- [ ] Create first GitHub repository. https://github.com/jfgossage/issues/4
- [ ] Clone or fork repository to local machine. https://github.com/jfgossage/issues/5
- [ ] Configure Mylyn to use GitHub as the task repository. https://github.com/jfgossage/issues/6
- [ ]  Create first task. https://github.com/jfgossage/issues/7
- [ ] Submit it to GitHub. https://github.com/jfgossage/issues/8
